{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vauthenticator.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.application.server.servlet.contextPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "vauthenticator.name" . }}
                port:
                  number: {{ .Values.application.server.port }}
    {{- with .Values.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}
  {{ end }}