apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vauthenticator.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.application.ingress.class }}
    {{- with .Values.application.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.application.server.servlet.contextPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "vauthenticator.name" . }}
                port:
                  number: {{ .Values.application.server.port }}
      host: {{  .Values.application.ingress.host }}
    {{- with .Values.application.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}