apiVersion: v1
kind: Service
metadata:
  name: {{ include "vauthenticator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vauthenticator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.application.server.port }}
      name: http
  selector:
    {{- include "vauthenticator.selectorLabels" . | nindent 4 }}
