version: 2
executorType: machine
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: mvn clean install -DskipTests
      - run: docker build -t mrflick72/vauthenticator:1.0.3 .