version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: mvn clean install
      - run: mvn docker:build