version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    working_directory: /tmp
    steps:
      - checkout
      - run: mvn clean install -DskipTests
      - persist_to_workspace:
          root: workspace
          paths:
            - target

  docker-publish:
    machine: true
    working_directory: /tmp
    steps:
      - attach_workspace:
          - /tmp/workspace/target
      - checkout
      - run: docker build -t mrflick72/vauthenticator:1.0.3 .

workflows:
  build-and-publish:
    jobs:
      - build
      - docker-publish:
          requires:
            - build