version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: mvn clean install -DskipTests
  docker-publish:
    machine:
    steps:
      - run: docker build -t mrflick72/vauthenticator:1.0.3 .