version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      resource_class: large
      docker_layer_caching: true

    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
      - checkout
      - run: mvn clean install -T2C