version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  localstack:
    #    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:3.2
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8050}:${PORT_WEB_UI-8080}"
    environment:
      - PERSISTENCE=1
      - SERVICES=s3,kms,dynamodb,iam,sts,sns
    volumes:
      - ./localstack:/var/lib/localstack
  redis:
    image: redis
    ports:
      - "6379:6379"
  mail-server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
