name: build vauthenticator

on:
  push: { }
  workflow_dispatch:
    inputs:
      version:
        description: 'make a tag'
        required: false


jobs:
  template-loading:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: load templates on s3
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          TEMPLATES=("welcome.html" "mail-verify-challenge.html" "reset-password.html" "successful-mail-verify.html")
          for TEMPLATE in ${TEMPLATES[@]}
          do 
            aws s3 cp communication/default/mail/$TEMPLATE s3://${{ secrets.VAUTHENTICATOR_BUCKET }}/mail/templates/$TEMPLATE
          done

  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: make an echo
        run: |
          echo version ${{github.event.inputs.version}}
          

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'


      - name: build testing environment
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          cd src/test/resources
          docker-compose up &
          sleep 80s
          sudo chown -R $USER:$USER *
          chmod 777 -R docker/dynamodb

          aws s3api create-bucket --bucket bucket --endpoint http://localhost:4566 --region us-east-1
          aws s3 cp  index.html s3://bucket/mail/templates/welcome.html --endpoint http://localhost:4566 --region us-east-1

      - name: Build frontend artifacts
        run: |
          cd src/main/frontend
          npm install --legacy-peer-deps
          npm run-script build

      - name: Build
        run: |
          mvn install -q

      - name: Create tag
        if: ${{github.event.inputs.version}} != ''

        uses: ncipollo/release-action@v1
        with:
          tag: ${{github.event.inputs.version}}
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}

      - name: docker push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          
          if [[ ${GITHUB_REF##*/} == 'master' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          
          echo "$DOCKER_TAG"
          docker build . -t mrflick72/vauthenticator-k8s:$DOCKER_TAG
          docker push mrflick72/vauthenticator-k8s:$DOCKER_TAG
          
          
          if [[ ${{github.event.inputs.version}} != '' ]]
          then
            DOCKER_TAG="${{github.event.inputs.version}}"
            docker build . -t mrflick72/vauthenticator-k8s:$DOCKER_TAG
            docker push mrflick72/vauthenticator-k8s:$DOCKER_TAG
          fi