name: build

on:
  push: { }
  workflow_dispatch: { }

jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-11-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
          java -version

      - name: run testing environment
        run: |
          cd src/test/resources
          docker-compose up &
          sleep 30s
          sudo chown -R  $USER *
          chmod 775 -R docker/dynamodb

      - name: build testing environment
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Build
        run: |
          mvn clean install -DskipTests

      - name: Test
        run: |
          mvn test

      - name: docker push
        run: |
          if [[ ${GITHUB_REF##*/} == 'master' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          echo "$DOCKER_TAG"
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build . -t mrflick72/vauthenticator-k8s:$DOCKER_TAG
          docker push mrflick72/vauthenticator-k8s:$DOCKER_TAG
